name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - run: go build -ldflags="-s -w"

      - uses: actions/upload-artifact@v2
        with:
          name: 'evec'
          path: 'evec'

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: 'evec'

      - id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: 'evec'
          asset_path: 'evec'
          asset_content_type: application/octet-stream
